# Generated by Django 4.0.1 on 2022-01-18 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('withdrawn_by', models.CharField(blank=True, max_length=255, null=True)),
                ('deposited_by', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(max_length=255)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('deposited_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.IntegerField()),
                ('reference_id', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('owned_by', models.CharField(max_length=255)),
                ('status', models.CharField(default='disable', max_length=255)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('balance', models.IntegerField()),
            ],
        ),
    ]
